[package]
name = "machine"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
clap = { version = "4.5.56", features = ["derive"] }
crossbeam = "0.8.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
uuid = { version = "1.20.0", features = ["v4"] }
